<?php 
/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function lottos_help($path,$arg){
	switch ($path) {
    	case "admin/help#lottos":
      		return '<p>' . t("Display lottos help") . '</p>';
      		break;
	}
}

/**
 * Implements hook_block_info().
 */
function lottos_block_info() {
    $blocks['lottos'] = array(
        // The name that will appear in the block list.
        'info' => t('Lottos info'),
        // Default setting.
        'cache' => DRUPAL_CACHE_PER_ROLE,
    );
    return $blocks;
}

function lottos_block_view($type){
    switch($type){
        case 'lottos':
            $block['subject'] = t('Lottos Results');
            if (user_access('access content')) {
                // Use our custom function to retrieve data.
                $result = lottos_history_contents();
                $items = array();
                foreach($result as $item){
                    $items[] = array('data'=>$item->type.':'.$item->code);
                }
                // No content in the last week.
                if (empty($items)) {
                    $block['content'] = t('No Lottos available.');
                }
                else {
                    // Pass data through theme function.
                    $block['content'] = theme('item_list', array(
                        'items' => $items));
                }
            }
            return $block;
            break;
    }
}

/**
 * Implements hook_menu().
 */
function lottos_menu() {
    $items = array();

    $items['admin/config/content/lottos'] = array(
        'title' => 'Lottos Results',
        'description' => 'Configuration for Lottos module',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('lottos_form'),
        'access arguments' => array('access administration pages'),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

function lottos_history_contents(){
    $query = db_select('lottos','n')
    ->fields('n', array('id', 'type', 'code'))
    ->orderBy('id', 'DESC')
    ->execute()
    ->fetchAll();
    return $query;
}